config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: { registrations: 'users/registrations', sessions: "users/sessions" }
	get '/categories', to: 'businesses#index'
	get '/recommendations', to: 'businesses#recommendations', as: 'recommendations'
  get 'business/:id', to: 'businesses#show', as: 'business_detail'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root "users#index"
	resources :users do
		collection do
			get 'questions', as: 'questions'
			post 'answer', as: 'answer'
		end
	end

	resources :reviews do 
		collection do 
			post 'new', as: 'new'
		end 
	end 
end

app/controllers/businesses_controller.rb
require 'json'
class BusinessesController < ApplicationController
  before_action :get_user_data

  def index
    @categories = Business.new.get_all_categories
   
  end

  def recommendations
    @all_prices = {'$'=>"1",'$$' => "2",'$$$' => "3", '$$$$' => "4"}
    @all_ratings = {'1.0'=>1,'2.0' => 2,'3.0' => 3,'4.0' => 4,'5.0' => 5}

    print @user
    if @user.nil? 
      redirect_to questions_users_path
      return
    end
   # if there is a category
    if !params[:category].nil?
      @category = params[:category]
      print @user.as_json
      zip_code = @user.zip_code if @user
      latitude = @user.latitude if @user
      longitude = @user.longitude if @user
      cds = {:lat => latitude.to_f, :lng => longitude.to_f}
      bounding_box = helpers.coordinates_to_miles(cds, 1)
      top_latitude = bounding_box[0]
      top_longitude = bounding_box[1]
      bottom_latitude = bounding_box[2]
      bottom_longitude = bounding_box[3]
      locations = {:top => [top_latitude, top_longitude], :bottom => [bottom_latitude, bottom_longitude]}
      @prices_to_show = @all_prices
      @ratings_to_show = @all_ratings
      if params[:prices]
        @prices_to_show = params[:prices]
      elsif session[:prices]
        @prices_to_show = session[:prices]
      end
      if params[:ratings]
        @ratings_to_show = params[:ratings]
      elsif session[:ratings]
        @ratings_to_show = session[:ratings]
      end
      session[:prices] = @prices_to_show
      session[:ratings] = @ratings_to_show
      @businesses = Business.businesses_with_ratings_prices(@category, @ratings_to_show.keys, @prices_to_show.keys, locations)
      coords = []
      @businesses.each_with_index do |cd, i| 
        cd_json = cd.as_json
        coos = [cd_json['latitude'], cd_json['longitude']]
        coords.push(coos)
      end
      # puts coords
      @distances = helpers.relative_distances_for_all_businesses(cds, coords)
      @businesses = @businesses.zip(@distances).sort_by{ |business,distance| distance}
    else
      redirect_to categories_path
    end
    #  redirect_to recommendations_path(:category => @category, :ratings => @all_ratings, :prices => @all_prices)
  end

  def show
    id = params[:id]
    @business = Business.find(id)
    @working_hours = JSON.parse @business.working_hours
    @rating = Review.get_rating(id)
    @features = @business.special_features.split(',')
    @reviews = Review.get_reviews(id).order(created_at: :desc).paginate(page: params[:page], per_page: 2)
  end
  
  protected

  def get_user_data
    if user_signed_in?
      @user = current_user
    elsif session["user"] && (User.clean_answers session["user"])
      @user = User.create_guest session["user"]
    else
      flash.alert = "Warning, you are not logged in and you haven't answered the questions."
    end
  end


  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def filter_params
    params.require(:business).permit(:category, :rating, :price, :address)
  end

end

app/views/businesses/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Jarvis</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <!-- <%= stylesheet_link_tag :recommendations %> -->
  </head>
  <body>
   
<main>

  <section class="text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Categories</h1>
        <p class="lead text-muted">Please select a business category.</p>
        
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @categories.each do |category| %>
        <div class="col">
          <div class="card shadow-sm">
          <%= image_tag(category + '.jpg', class:"card-img-top", style:"object-fit:cover; object-position: bottom;width:100%; height:225px;") %>
            <%# <img src="/assets/joes.jpg" class="card-img-top" style="object-fit:cover; object-position: bottom;width:100%; height:225px;"> %>
            <div class="card-body">
              <%# <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p> %>
               <div class="d-flex justify-content-between align-items-center">
                 <p> <%= category.capitalize %> </p>
               </div>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to "See Recommendations", recommendations_path(:category => category), class:"btn btn-sm btn-outline-secondary", id: category %>
                  <%# <button type="button" class="btn btn-sm btn-outline-secondary" >See Recommendations</button> %>
                  
                </div>
                <%# <small class="text-muted"> <%= business.price  </small> %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </main> 
  <%= javascript_include_tag 'recommendations' %> 
  </body>
</html>

app/views/businesses/recommendations.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Jarvis</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <%= stylesheet_link_tag :recommendations %>
  </head>
  <body>
  <main>
    <section class="text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Recommendations</h1>
          <p class="lead text-muted">Here Are Your <%= params[:category].capitalize %> Recommendations</p>
          <%= link_to "Back to Categories", categories_path, class:"btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
    </section>
    
    <div class="container">
      <%= form_tag recommendations_path, method: :get, id: 'filters_form' do %>
      <div class="row text-center j-left">
        <div class="col-sm-12 text-left">
          <h3>Filters</h3>
        </div>
        <div class="col-sm-auto">
          Prices:
            <% @all_prices.keys.each do |price| %>
              <div class="form-check form-check-inline">
                <%= label_tag "prices[#{price}]", price, class: 'form-check-label' %>
                <%= check_box_tag "prices[#{price}]", "1",  @prices_to_show.include?(price), class: 'form-check-input' %>
              </div>
            <% end %>
        </div>
        <div class="col-sm-auto">
          Ratings:
          <% @all_ratings.keys.each do |rating| %>
            <div class="form-check  form-check-inline">
              <%= label_tag "ratings[#{rating}]", rating, class: 'form-check-label' %>
              <%= check_box_tag "ratings[#{rating}]", "1",  @ratings_to_show.include?(rating), class: 'form-check-input' %>
            </div>
          <% end %>
          <input type="hidden" name="category" value="<%= @category %>"/>
        </div>
        <div class="col-sm-auto">
          <%= submit_tag 'Refresh', id: 'filters_submit', class: 'btn-primary btn-sm' %>
        </div>
      </div>
      <% end %>
    </div>
    <div class="album py-5 bg-light">
      <section class="container">
        <h1> <%= params[:category].nil? ? 'Recommendations' : params[:category].capitalize  %> </h1>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% if @businesses.nil? || @businesses.length() == 0%>
          <div class="col w-100 my-4">
            <h4>No recommendations found for the filter and location you have selected.</h4>
          </div>
        <% else %>
          <% @businesses.each_with_index do |tuple, index| %>
          <div class="col business">
            <div class="<%= index == 0 ? "banner show" : "hide" %>">CLOSEST</div>
            <div class="card shadow-sm">
                <%= image_tag((tuple[0]['img_url'] == '' ? tuple[0].category + '.jpg' : tuple[0].img_url), class: "card-img-top", style: 'object-fit:cover; object-position: center;width:100%; height:225px;') %>
                <div class="card-body">
                  <div class="d-flex justify-content-between align-items-center">
                    <p>  <%= link_to tuple[0].name , business_detail_path(:id => tuple[0].id)%></p>
                    <small class="text-muted rating" style="margin-bottom: 1rem;"> <%= tuple[0].rating %>/5.0 </small>
                  </div>
                  <div class="d-flex justify-content-between align-items-center">
                    <p style="text-align: left;" class="text-muted"><%= tuple[0].display_phone %></p>
                    <small class="text-muted"> <%= tuple[0].price %></small>
                  </div>
                  <div class="d-flex justify-content-between align-items-center">
                    <a style="outline:none;color:#000;text-decoration:none;border:1px solid #000; padding: 0rem 0.5rem;" href="tel:" + <%= tuple[0].phone %>>Call</a>
                    <p class="text-muted" style="margin-top:auto;margin-bottom:auto;margin-left:1rem;"><%= tuple[0].address %>,&nbsp;<%= tuple[0].zip_code %> </p>
                  </div>
                </div>
              </div>
          </div>
          <% end %>
        <% end %>
        </div>
      </section>
    </div>
  </main>
  <%= javascript_include_tag 'recommendations' %> 

  <%# <script src="js/scripts.js"></script> %>
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </body>
</html>

app/views/businesses/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<%= stylesheet_link_tag :styles %>
<%= stylesheet_link_tag :business_detail %>


    <div class="container">
        <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
            
            <div class="col-lg-6">
                <%= image_tag((@business['img_url'] == '' ? @business.category + '.jpg' : @business.img_url), class: "card-img-top", style: 'object-fit:cover; object-position: center;width:100%; height:225px;') %>
            </div>

            <div class="col-lg-6">
                <div class="bg-black text-center h-100 project">
                    <div class="d-flex h-100">
                        <div class="project-text w-100 my-auto text-center text-lg-left">
                            <h4 class="text-white"><%= @business.name %></h4>
                            <p class="mb-0 text-white-50"><%= @business.category %></p>
                            <p class="mb-0 text-white-50"><%= @business.address %></p>
                            <p class="mb-0 text-white-50">Rating: <%= @rating %></p>
                            <hr class="d-none d-lg-block mb-0 ms-0" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="row info">
                <div class="col-lg-8">
                    <h4>Location</h4>
                    <div id="map" class="mb-4"></div>
                     <% if @features.length() != 0 %>
                    <h4>Special features</h4>
                     <ul>
                        <% @features.each do |f| %>
                            <li style="text-transform: capitalize;"><%= f %></li>
                        <% end %>
                        </ul>
                    <% end%>
                </div>

                
                <div id="working-hours" class="col-lg-4">
                <% if @working_hours %>
             
                    <h4>Working hours</h4>
                    <table>
                    <% @working_hours.each do |day| %>
                        <tr>
                            <td><%= day["day"]%> </td>
                            <td><%= day["start"]%> - <%= day["end"]%></td>
                        </tr>
                    <% end %>
                        </table>
                </div>
                <% end %>
            </div>

            <div class="row ratings">
            
            <h3>Reviews</h3>
            <p class="font-weight-light mt-2">Leave your review here</p>
                <div class="col-lg-12 mb-4">
                    <% if user_signed_in? %>
                    <%= form_with model: Review.new, url: new_reviews_path, :html => { :id => "review-form" } do |form| %>
                    <div class="txt-center">
                            <div class="rating">

                                <%= form.collection_radio_buttons :rating, [[5], [4], [3], [2], [1]], :first, :last, item_wrapper_tag: false, boolean_style: :inline do |b| %>
                                <%= b.radio_button :class => 'radio-btn hide',  required: true  %>
                                <%= b.label {'☆'} %>
                                <% end %>

                                <div class="clear"></div>
                            </div>
                        </div>
                        <%= form.text_field :title, placeholder: "Title", required: true %>
                        <%= form.text_area :comment, placeholder: "Your review here", required: true %>
                        <%= form.hidden_field :user_id, :value => current_user.id %>
                        <%= form.hidden_field :business_id, :value => @business.id %>
                        <%= form.submit "Submit"%>
                    <% end %>
                        
                    <% else %>
                        <%= link_to "Sign in", new_user_session_path %> 
                        or <%= link_to "Sign up", new_user_registration_path %> to leave a review 
                    <% end %>
                </div>

                <div class="col-lg-12">
                        

                        <% if @reviews.any? %>
                            <% @reviews.each do |review| %>

                            <div class="box">  
                                <%= image_tag "user_profile_placeholder.png", class: "img-fluid"%>
                            </div>
                            
                            <div class="review-content">
                            <p>
                                <% if review.user.email.blank? %>
                                    Anonymous</p>
                                <% else %> 
                                    <b><%= review.user.email %></b>
                                <% end %>
                                <p id="review_date"> <%= review.created_at.strftime("%m/%d/%y") %></p>
                                
                                <p> <%= review.title %></p>
                                
                            </div>

                            <div>   
                                <p> Rating: <% (1..review.rating).each do |n| %> 
                                            <span class="fa fa-star checked"></span>
                                            <% end %>
                            </div>

                            <div>   
                                <p> <%= review.comment %></p>
                            </div>

                    <% end %>
                    <% else %>
                        <p>No reviews at the moment.</p>
                    <% end %>
                      <%= will_paginate @reviews, renderer: WillPaginate::ActionView::BootstrapLinkRenderer  %>
                </div>

            </div>
            <input type="hidden" id="latitude" value=<%= @business["latitude"]%>>
            <input type="hidden" id="longitude" value=<%= @business["longitude"]%>>
    </div>
    
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB6PSLv2kH7tsrxGbRwovIVe6jF9Zrw8Ak&callback=initMap&libraries=&v=weekly&" async></script>

    <script> 
        function initMap() {
        // The location of Uluru
        const lat = parseFloat($('#latitude').val())
        const long = parseFloat($('#longitude').val())
        const uluru = { lat: lat, lng: long };
        // The map, centered at Uluru
        const map = new google.maps.Map(document.getElementById("map"), {
            zoom: 14,
            center: uluru,
        });
        // The marker, positioned at Uluru
        const marker = new google.maps.Marker({
            position: uluru,
            map: map,
        });
        }
</script>