config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: { registrations: 'users/registrations', sessions: "users/sessions" }
	get '/categories', to: 'businesses#index'
	get '/recommendations', to: 'businesses#recommendations', as: 'recommendations'
  get 'business/:id', to: 'businesses#show', as: 'business_detail'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root "users#index"
	resources :users do
		collection do
			get 'questions', as: 'questions'
			post 'answer', as: 'answer'
		end
	end

	resources :reviews do 
		collection do 
			post 'new', as: 'new'
		end 
	end 
end

app/models/user.rb
require 'securerandom'

class User < ApplicationRecord
	validates_presence_of :from_country, :address, :work, :budget, :zip_code, :latitude, :longitude
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
		   :recoverable, :rememberable, :validatable
	enum work: { student: 0, professional: 1 }

	cattr_reader :questions, :types, :placeholders, :countries
	@@questions = {
		from_country: "Which country are you coming from?",
		address: "Which city are you traveling to?",
		work: "What is your work category?",
		budget: "What is your budget?",
		latitude: "",
		longitude: ""
	}
	@@types = {
	 	from_country: :string,
    	address: :string,
	  	work: :integer,
	  	budget: :integer,
    	zip_code: :integer,
    	latitude: :float,
    	longitude: :float
	}
	@@placeholders = {
		from_country: "India",
		address: "2960 Broadway",
		work: "Student/Professional",
		budget: "2000"
	}

	@@countries = [
		["Select Country", "Select Country"],
		["Afghanistan", "Afghanistan"],
		["Albania", "Albania"],
		["Algeria", "Algeria"],
		["American Samoa", "American Samoa"],
		["Andorra", "Andorra"],
		["Angola", "Angola"],
		["Anguilla", "Anguilla"],
		["Antarctica", "Antarctica"],
		["Antigua and Barbuda", "Antigua and Barbuda"],
		["Argentina", "Argentina"],
		["Armenia", "Armenia"],
		["Aruba", "Aruba"],
		["Australia", "Australia"],
		["Austria", "Austria"],
		["Azerbaijan", "Azerbaijan"],
		["Bahamas (the)", "Bahamas (the)"],
		["Bahrain", "Bahrain"],
		["Bangladesh", "Bangladesh"],
		["Barbados", "Barbados"],
		["Belarus", "Belarus"],
		["Belgium", "Belgium"],
		["Belize", "Belize"],
		["Benin", "Benin"],
		["Bermuda", "Bermuda"],
		["Bhutan", "Bhutan"],
		["Bolivia (Plurinational State of)", "Bolivia (Plurinational State of)"],
		["Bonaire, Sint Eustatius and Saba", "Bonaire, Sint Eustatius and Saba"],
		["Bosnia and Herzegovina", "Bosnia and Herzegovina"],
		["Botswana", "Botswana"],
		["Bouvet Island", "Bouvet Island"],
		["Brazil", "Brazil"],
		["British Indian Ocean Territory (the)", "British Indian Ocean Territory (the)"],
		["Brunei Darussalam", "Brunei Darussalam"],
		["Bulgaria", "Bulgaria"],
		["Burkina Faso", "Burkina Faso"],
		["Burundi", "Burundi"],
		["Cabo Verde", "Cabo Verde"],
		["Cambodia", "Cambodia"],
		["Cameroon", "Cameroon"],
		["Canada", "Canada"],
		["Cayman Islands (the)", "Cayman Islands (the)"],
		["Central African Republic (the)", "Central African Republic (the)"],
		["Chad", "Chad"],
		["Chile", "Chile"],
		["China", "China"],
		["Christmas Island", "Christmas Island"],
		["Cocos (Keeling) Islands (the)", "Cocos (Keeling) Islands (the)"],
		["Colombia", "Colombia"],
		["Comoros (the)", "Comoros (the)"],
		["Congo (the Democratic Republic of the)", "Congo (the Democratic Republic of the)"],
		["Congo (the)", "Congo (the)"],
		["Cook Islands (the)", "Cook Islands (the)"],
		["Costa Rica", "Costa Rica"],
		["Croatia", "Croatia"],
		["Cuba", "Cuba"],
		["Curaçao", "Curaçao"],
		["Cyprus", "Cyprus"],
		["Czechia", "Czechia"],
		["Côte d'Ivoire", "Côte d'Ivoire"],
		["Denmark", "Denmark"],
		["Djibouti", "Djibouti"],
		["Dominica", "Dominica"],
		["Dominican Republic (the)", "Dominican Republic (the)"],
		["Ecuador", "Ecuador"],
		["Egypt", "Egypt"],
		["El Salvador", "El Salvador"],
		["Equatorial Guinea", "Equatorial Guinea"],
		["Eritrea", "Eritrea"],
		["Estonia", "Estonia"],
		["Eswatini", "Eswatini"],
		["Ethiopia", "Ethiopia"],
		["Falkland Islands (the) [Malvinas]", "Falkland Islands (the) [Malvinas]"],
		["Faroe Islands (the)", "Faroe Islands (the)"],
		["Fiji", "Fiji"],
		["Finland", "Finland"],
		["France", "France"],
		["French Guiana", "French Guiana"],
		["French Polynesia", "French Polynesia"],
		["French Southern Territories (the)", "French Southern Territories (the)"],
		["Gabon", "Gabon"],
		["Gambia (the)", "Gambia (the)"],
		["Georgia", "Georgia"],
		["Germany", "Germany"],
		["Ghana", "Ghana"],
		["Gibraltar", "Gibraltar"],
		["Greece", "Greece"],
		["Greenland", "Greenland"],
		["Grenada", "Grenada"],
		["Guadeloupe", "Guadeloupe"],
		["Guam", "Guam"],
		["Guatemala", "Guatemala"],
		["Guernsey", "Guernsey"],
		["Guinea", "Guinea"],
		["Guinea-Bissau", "Guinea-Bissau"],
		["Guyana", "Guyana"],
		["Haiti", "Haiti"],
		["Heard Island and McDonald Islands", "Heard Island and McDonald Islands"],
		["Holy See (the)", "Holy See (the)"],
		["Honduras", "Honduras"],
		["Hong Kong", "Hong Kong"],
		["Hungary", "Hungary"],
		["Iceland", "Iceland"],
		["India", "India"],
		["Indonesia", "Indonesia"],
		["Iran (Islamic Republic of)", "Iran (Islamic Republic of)"],
		["Iraq", "Iraq"],
		["Ireland", "Ireland"],
		["Isle of Man", "Isle of Man"],
		["Israel", "Israel"],
		["Italy", "Italy"],
		["Jamaica", "Jamaica"],
		["Japan", "Japan"],
		["Jersey", "Jersey"],
		["Jordan", "Jordan"],
		["Kazakhstan", "Kazakhstan"],
		["Kenya", "Kenya"],
		["Kiribati", "Kiribati"],
		["Korea (the Democratic People's Republic of)", "Korea (the Democratic People's Republic of)"],
		["Korea (the Republic of)", "Korea (the Republic of)"],
		["Kuwait", "Kuwait"],
		["Kyrgyzstan", "Kyrgyzstan"],
		["Lao People's Democratic Republic (the)", "Lao People's Democratic Republic (the)"],
		["Latvia", "Latvia"],
		["Lebanon", "Lebanon"],
		["Lesotho", "Lesotho"],
		["Liberia", "Liberia"],
		["Libya", "Libya"],
		["Liechtenstein", "Liechtenstein"],
		["Lithuania", "Lithuania"],
		["Luxembourg", "Luxembourg"],
		["Macao", "Macao"],
		["Madagascar", "Madagascar"],
		["Malawi", "Malawi"],
		["Malaysia", "Malaysia"],
		["Maldives", "Maldives"],
		["Mali", "Mali"],
		["Malta", "Malta"],
		["Marshall Islands (the)", "Marshall Islands (the)"],
		["Martinique", "Martinique"],
		["Mauritania", "Mauritania"],
		["Mauritius", "Mauritius"],
		["Mayotte", "Mayotte"],
		["Mexico", "Mexico"],
		["Micronesia (Federated States of)", "Micronesia (Federated States of)"],
		["Moldova (the Republic of)", "Moldova (the Republic of)"],
		["Monaco", "Monaco"],
		["Mongolia", "Mongolia"],
		["Montenegro", "Montenegro"],
		["Montserrat", "Montserrat"],
		["Morocco", "Morocco"],
		["Mozambique", "Mozambique"],
		["Myanmar", "Myanmar"],
		["Namibia", "Namibia"],
		["Nauru", "Nauru"],
		["Nepal", "Nepal"],
		["Netherlands (the)", "Netherlands (the)"],
		["New Caledonia", "New Caledonia"],
		["New Zealand", "New Zealand"],
		["Nicaragua", "Nicaragua"],
		["Niger (the)", "Niger (the)"],
		["Nigeria", "Nigeria"],
		["Niue", "Niue"],
		["Norfolk Island", "Norfolk Island"],
		["Northern Mariana Islands (the)", "Northern Mariana Islands (the)"],
		["Norway", "Norway"],
		["Oman", "Oman"],
		["Pakistan", "Pakistan"],
		["Palau", "Palau"],
		["Palestine, State of", "Palestine, State of"],
		["Panama", "Panama"],
		["Papua New Guinea", "Papua New Guinea"],
		["Paraguay", "Paraguay"],
		["Peru", "Peru"],
		["Philippines (the)", "Philippines (the)"],
		["Pitcairn", "Pitcairn"],
		["Poland", "Poland"],
		["Portugal", "Portugal"],
		["Puerto Rico", "Puerto Rico"],
		["Qatar", "Qatar"],
		["Republic of North Macedonia", "Republic of North Macedonia"],
		["Romania", "Romania"],
		["Russian Federation (the)", "Russian Federation (the)"],
		["Rwanda", "Rwanda"],
		["Réunion", "Réunion"],
		["Saint Barthélemy", "Saint Barthélemy"],
		["Saint Helena, Ascension and Tristan da Cunha", "Saint Helena, Ascension and Tristan da Cunha"],
		["Saint Kitts and Nevis", "Saint Kitts and Nevis"],
		["Saint Lucia", "Saint Lucia"],
		["Saint Martin (French part)", "Saint Martin (French part)"],
		["Saint Pierre and Miquelon", "Saint Pierre and Miquelon"],
		["Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"],
		["Samoa", "Samoa"],
		["San Marino", "San Marino"],
		["Sao Tome and Principe", "Sao Tome and Principe"],
		["Saudi Arabia", "Saudi Arabia"],
		["Senegal", "Senegal"],
		["Serbia", "Serbia"],
		["Seychelles", "Seychelles"],
		["Sierra Leone", "Sierra Leone"],
		["Singapore", "Singapore"],
		["Sint Maarten (Dutch part)", "Sint Maarten (Dutch part)"],
		["Slovakia", "Slovakia"],
		["Slovenia", "Slovenia"],
		["Solomon Islands", "Solomon Islands"],
		["Somalia", "Somalia"],
		["South Africa", "South Africa"],
		["South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands"],
		["South Sudan", "South Sudan"],
		["Spain", "Spain"],
		["Sri Lanka", "Sri Lanka"],
		["Sudan (the)", "Sudan (the)"],
		["Suriname", "Suriname"],
		["Svalbard and Jan Mayen", "Svalbard and Jan Mayen"],
		["Sweden", "Sweden"],
		["Switzerland", "Switzerland"],
		["Syrian Arab Republic", "Syrian Arab Republic"],
		["Taiwan", "Taiwan"],
		["Tajikistan", "Tajikistan"],
		["Tanzania, United Republic of", "Tanzania, United Republic of"],
		["Thailand", "Thailand"],
		["Timor-Leste", "Timor-Leste"],
		["Togo", "Togo"],
		["Tokelau", "Tokelau"],
		["Tonga", "Tonga"],
		["Trinidad and Tobago", "Trinidad and Tobago"],
		["Tunisia", "Tunisia"],
		["Turkey", "Turkey"],
		["Turkmenistan", "Turkmenistan"],
		["Turks and Caicos Islands (the)", "Turks and Caicos Islands (the)"],
		["Tuvalu", "Tuvalu"],
		["Uganda", "Uganda"],
		["Ukraine", "Ukraine"],
		["United Arab Emirates (the)", "United Arab Emirates (the)"],
		["United Kingdom of Great Britain and Northern Ireland (the)", "United Kingdom of Great Britain and Northern Ireland (the)"],
		["United States Minor Outlying Islands (the)", "United States Minor Outlying Islands (the)"],
		["United States of America (the)", "United States of America (the)"],
		["Uruguay", "Uruguay"],
		["Uzbekistan", "Uzbekistan"],
		["Vanuatu", "Vanuatu"],
		["Venezuela (Bolivarian Republic of)", "Venezuela (Bolivarian Republic of)"],
		["Viet Nam", "Viet Nam"],
		["Virgin Islands (British)", "Virgin Islands (British)"],
		["Virgin Islands (U.S.)", "Virgin Islands (U.S.)"],
		["Wallis and Futuna", "Wallis and Futuna"],
		["Western Sahara", "Western Sahara"],
		["Yemen", "Yemen"],
		["Zambia", "Zambia"],

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_action :configure_permitted_parameters

	def create
		params["user"] = params["user"].merge(session["user"])
		session.delete "user"
		super
	end

	def new
		unless (! session["user"].nil?) && (User.clean_answers session["user"])
			redirect_to questions_users_path
		else
			super
		end
	end

	# PUT /resource
	# We need to use a copy of the resource because we don't want to change
	# the current user in place.
	def update
		self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
		prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

		account_update = account_update_params
		account_update = User.infer_zip_code account_update
		unless account_update
			redirect_to edit
			return
		end
		resource_updated = update_resource(resource, account_update)

		yield resource if block_given?
		if resource_updated
			set_flash_message_for_update(resource, prev_unconfirmed_email)
			bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

			respond_with resource, location: after_update_path_for(resource)
		else
			clean_up_passwords resource
			set_minimum_password_length
			respond_with resource
		end
	end

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:from_country, :address, :work, :budget, :zip_code, :latitude, :longitude, :name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:from_country, :address, :work, :budget, :zip_code, :latitude, :longitude, :name])
	end

	def after_sign_up_path_for(resource)
		categories_path
	end

	def after_inactive_sign_up_path_for(resource)
		categories_path
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	protected

	def after_sign_in_path_for(resource)
		categories_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		redirect_to root_path
	end

	def answer
		begin
			answers = answers_params
		rescue ActionController::UnpermittedParameters
			flash.alert = "Sorry, un-permitted parameters were provided. Please try again."
			redirect_to questions_users_path
		else
			answers = answers.to_h
			answers = User.clean_and_complete answers
			unless answers
				flash.alert = "Sorry, we were unable to parse your answers. Please try again."
				redirect_to questions_users_path
			else
				session[:user] = answers
				if params[:create_account]
					redirect_to new_user_registration_path
				else
					redirect_to categories_path
				end
			end
		end
	end

	def questions
		@questions = User.questions
		@placeholders = User.placeholders
		@countries = User.countries
		render :questions
	end

	private

	def answers_params
		ActionController::Parameters.action_on_unpermitted_parameters = :raise
		params.require(:user).permit(:from_country, :address, :work, :budget, :zip_code, :latitude, :longitude)
	end
end

app/helpers/users_helper.rb
module UsersHelper
  # Calculates distance between two coordinates. Not taken square root here as a greater distance will have this value greater regardless of a square root.
  # Parameters: Two coordinate objects. Coordinate object -> {lat:<Latitude_Value>,lng:<Longitude_Value>}
  def distance_between_coordinates(cd_1, cd_2)
    return Math.sqrt(((cd_1[:lat]-cd_2[:lat])**2) + ((cd_1[:lng]-cd_2[:lng])**2))
  end

  # 
  def relative_distances_for_all_businesses(source_cd, cds)
    distances = []
    cds.each do |cd| 
      d = Geocoder::Calculations.distance_between([source_cd[:lat], source_cd[:lng]], cd)
      # d = distance_between_coordinates(source_cd, {:lat => cd["latitude"].to_f, :lng => cd["latitude"].to_f})
      distances.push(d)
    end
    return distances
  end

  def coordinates_to_miles(coordinates, miles)
    latitude = coordinates[:lat]
    longitude = coordinates[:lng]
    cds = Geocoder::Calculations.bounding_box([latitude, longitude], miles)
    return cds
    # 1 latitude degree ~ 69 miles
    top_latitude = latitude + miles * (1/69.to_f);
    bottom_latitude = latitude - miles* (1/69.to_f);

    # 1 degree of Longitude = cosine (latitude in decimal degrees) * length of degree (miles) at equator
    top_longitude = Math.cos(top_latitude) * 69
    bottom_longitude = Math.cos(bottom_latitude) * 69
    # puts coordinates
    # return [{:lat => top_latitude, :lng => top_longitude}, {:lat => bottom_latitude, :lng => bottom_longitude}]

   end
end

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Jarvis</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <%= stylesheet_link_tag :styles %>
        <%# <link href="stylesheets/styles.css" rel="stylesheet" /> %>
    </head>
    <body id="page-top">
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        <h1 class="mx-auto my-0 text-uppercase">Jarvis</h1>
                        <h2 class="text-white-50 mx-auto mt-2 mb-5">Your guide to living in a new city.</h2>
                        <%= link_to "Get Started", questions_users_path, class: "btn btn-primary"%>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                        <h2 class="text-white mb-4">You choose the city. We help you move.</h2>
                        <p class="text-white-50">
                            Jarvis is a personalized recommendation system for movers. Don't know where to buy hangers or 
                            where to eat the best tacos in an area? We're here to answer that. 
                        </p>
                    </div>
                </div>
                <%= image_tag "laptop.png", class: "img-fluid float-left w-90 ", alt: "..." %>
            </div>
        </section>
    
        <section class="projects-section bg-light" id="projects">
            <div class="container px-4 px-lg-5">
                <div class="row gx-0 mb-4 mb-4 ">
                    <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
                    <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
                    <div class="my-3 p-3" >
                        <h2 class="display-5">Feel Like Cooking?</h2>
                        <p class="lead">Browse our database for grocery stores</p>
                        <button type="button" class="btn btn-outline-secondary">
                        <a href="<%= recommendations_path(:category => "groceries") %>"> Browse </a>
                        </button>
                    </div>
                    </div>
                    <div class="col-xl-8 col-lg-7"><%= image_tag "food-rec.jpg", class: "img-fluid mb-3 mb-lg-0", alt: "..."%></div>
                    
                   
                </div>
                <div class="row gx-0 mb-4 mb-4 ">
                <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
                <div class="col-xl-8 col-lg-7"><%= image_tag "hardware.jpg", class: "img-fluid mb-3 mb-lg-0", alt: "..."%></div>
                <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
                <div class="my-3 p-3">
                    <h2 class="display-5">Something Need Fixing?</h2>
                    <p class="lead">Browse our database for hardware stores</p>
                    <button type="button" class="btn btn-outline-secondary">
                        <a href="<%= recommendations_path(:category => "hardware") %>"> Browse </a>
                        </button>
                </div>
                </div>
            </div>

            <div class="row gx-0 mb-4 mb-4 ">

                <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
                <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
                <div class="my-3 p-3">
                    <h2 class="display-5">Feel Like Eating Out?</h2>
                    <p class="lead">Browse our database for restaurants</p>
                    <button type="button" class="btn btn-outline-secondary">
                        <a href="<%= recommendations_path(:category => "restaurants") %>"> Browse </a>
                        </button>
                </div>
                </div>
                <div class="col-xl-8 col-lg-7"><%= image_tag "restaurants.jpg", class: "img-fluid mb-3 mb-lg-0", alt: "..."%></div>
                </div>
                <div class="row gx-0 mb-4 mb-4 ">
                <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
                <div class="col-xl-8 col-lg-7"><%= image_tag "bank2.jpg", class: "img-fluid mb-3 mb-lg-0", alt: "..."%></div>
                <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
                <div class="my-3 p-3">
                    <h2 class="display-5">Need a Bank?</h2>
                    <p class="lead">Browse our database for banks</p>
                    <button type="button" class="btn btn-outline-secondary">
                        <a href="<%= recommendations_path(:category => "banks") %>"> Browse </a>
                        </button>
                </div>
                </div>
            </div>  
            </div>
        

        
         <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
         <div class="carousel-indicators">
         <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
         <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
         <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
         </div>
         <div class="carousel-inner">
         <div class="carousel-item active">
             <svg class="bd-placeholder-img" width="100%" height="300px" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#A9A9A9"/></svg>
 
             <div class="container">
             <div class="carousel-caption">
                 <h1>"I was nervous about moving to a new city but Jarvis made it a breeze."</h1>
                 <p style="text-align:center-right">-Ada Lovelace</p>
             </div>
             </div>
         </div>
         <div class="carousel-item">
             <svg class="bd-placeholder-img" width="100%" height="300px" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#A9A9A9"/></svg>
 
             <div class="container">
             <div class="carousel-caption">
                 <h1>"Jarvis is so helpful and easy to use, I recommend it to all my friends!"</h1>
                 <p style="text-align:center-right">-Mickey Mouse</p>
                 
             </div>
             </div>
         </div>
         <div class="carousel-item">
             <svg class="bd-placeholder-img" width="100%" height="300px" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#A9A9A9"/></svg>
 
             <div class="container">
             <div class="carousel-caption">
                 <h1>"10/10 would recommend! Better than everything else on the market!"</h1>
                 <p>-John Smith</p>
                 
             </div>
             </div>
         </div>
         </div>
         <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
         <span class="carousel-control-prev-icon" aria-hidden="true"></span>
         <span class="visually-hidden">Previous</span>
         </button>
         <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
         <span class="carousel-control-next-icon" aria-hidden="true"></span>
         <span class="visually-hidden">Next</span>
         </button>
     </div>    
     </section>
    </body>
</html>